apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: billing-processor-26295
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/billing-processor-26295
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
